{
 "title": "Nageru",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "nageru_latency_seconds{measuring_point=\"mixer\"}"
   },
   {
    "name": "card",
    "query": "nageru_latency_seconds{measuring_point=\"mixer\"}"
   }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Nageru uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - nageru_start_time_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk space remaining",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "nageru_disk_free_bytes / ignoring(destination) deriv(nageru_mux_written_bytes{destination=\"files_total\",instance=~\"$instance\"}[10m])"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nageru_num_connected_clients{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Connected FFmpeg inputs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nageru_input_has_signal_bool{cardtype=\"ffmpeg\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Overall audio level",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nageru_audio_loudness_integrated_lufs{instance=~\"$instance\"} + 23"
    }
   ]
  },
  {
   "title": "Audio correlation",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nageru_audio_correlation{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Potential performance problems",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nageru_decklink_output_completed_frames{status!=\"completed\",instance=~\"$instance\"}[1m])",
     "legendFormat": "Output frames {{status}}"
    },
    {
     "expr": "sum(rate(nageru_input_dropped_frames_error{instance=~\"$instance\"}[1m])) without (cardtype)",
     "legendFormat": "Error frames card {{card}}"
    },
    {
     "expr": "rate(nageru_quick_sync_stalled_frames{instance=~\"$instance\"}[1m])",
     "legendFormat": "Quick Sync stalled frames"
    },
    {
     "expr": "rate(nageru_x264_dropped_frames{instance=~\"$instance\"}[1m])",
     "legendFormat": "x264 dropped frames"
    },
    {
     "expr": "rate(nageru_x264_speedcontrol_idle_frames{instance=~\"$instance\"}[1m])",
     "legendFormat": "x264 speedcontrol idle frames"
    },
    {
     "expr": "rate(nageru_x264_speedcontrol_late_frames{instance=~\"$instance\"}[1m])",
     "legendFormat": "x264 speedcontrol late frames"
    }
   ]
  },
  {
   "title": "Queue events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nageru_input_queue_duped_frames{instance=~\"$instance\"}[1m])) without (cardtype)",
     "legendFormat": "Duplicated frames (queue starvation) card {{card}}"
    },
    {
     "expr": "sum(rate(nageru_input_dropped_frames_jitter{instance=~\"$instance\"}[1m])) without (cardtype)",
     "legendFormat": "Dropped frames card {{card}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Stream bitrates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(nageru_mux_stream_bytes{destination=\"http\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Disk bitrates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * rate(nageru_mux_stream_bytes{destination=\"current_file\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "x264 average CRF (lower is better)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(nageru_x264_crf_bucket{instance=~\"$instance\"}[1m]))",
     "legendFormat": "90-percentile"
    },
    {
     "expr": "histogram_quantile(0.1, rate(nageru_x264_crf_bucket{instance=~\"$instance\"}[1m]))",
     "legendFormat": "10-percentile"
    },
    {
     "expr": "rate(nageru_x264_crf_sum{instance=~\"$instance\"}[1m]) / rate(nageru_x264_crf_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "x264 speed control chosen preset",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "rate(nageru_x264_speedcontrol_preset_used_frames_bucket{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "x264 buffer space available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nageru_x264_speedcontrol_buffer_available_seconds{instance=~\"$instance\"} / nageru_x264_speedcontrol_buffer_size_seconds{instance=~\"$instance\"}",
     "legendFormat": "x264 speed control buffer available"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "HDMI/SDI latency, card $card",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "repeat": "card",
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "nageru_latency_seconds{measuring_point=\"decklink_output\",frame_type=\"total\",quantile=\"0.9\",frame_age=\"0\",card=\"$card\",instance=~\"$instance\"}",
     "legendFormat": "90-percentile"
    },
    {
     "expr": "nageru_latency_seconds{measuring_point=\"decklink_output\",frame_type=\"total\",quantile=\"0.1\",frame_age=\"0\",card=\"$card\",instance=~\"$instance\"}",
     "legendFormat": "10-percentile"
    },
    {
     "expr": "sum(\n  rate(nageru_latency_seconds_sum{measuring_point=\"decklink_output\",frame_age=\"0\",card=\"$card\",instance=~\"$instance\"}[1m])\n) without (frame_type) / sum(\n  rate(nageru_latency_seconds_count{measuring_point=\"decklink_output\",frame_age=\"0\",card=\"$card\",instance=~\"$instance\"}[1m])\n) without (frame_type)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Mixer latency, card $card",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "repeat": "card",
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "nageru_latency_seconds{measuring_point=\"mixer\",frame_type=\"total\",quantile=\"0.9\",frame_age=\"0\",card=\"$card\",instance=~\"$instance\"}",
     "legendFormat": "90-percentile"
    },
    {
     "expr": "nageru_latency_seconds{measuring_point=\"mixer\",frame_type=\"total\",quantile=\"0.1\",frame_age=\"0\",card=\"$card\",instance=~\"$instance\"}",
     "legendFormat": "10-percentile"
    },
    {
     "expr": "sum(\n  rate(nageru_latency_seconds_sum{measuring_point=\"mixer\",frame_age=\"0\",card=\"$card\",instance=~\"$instance\"}[1m])\n) without (frame_type) / sum(\n  rate(nageru_latency_seconds_count{measuring_point=\"mixer\",frame_age=\"0\",card=\"$card\",instance=~\"$instance\"}[1m])\n) without (frame_type)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nageru_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "nageru_memory_locked_limit_bytes{instance=~\"$instance\"}",
     "legendFormat": "Max locked"
    }
   ]
  }
 ]
}